services:
  re1:
    image: redislabs/redis:latest
    container_name: re1
    restart: unless-stopped
    tty: true
    cap_add: 
      - sys_resource
    ports:
      - 8443
      - 9443
      - 12000
    profiles: ["redis"]
    networks:
      re_cluster:
        ipv4_address: 192.168.20.2

  re2:
    image: redislabs/redis:latest
    container_name: re2
    restart: unless-stopped
    tty: true
    cap_add: 
      - sys_resource
    ports:
      - 8443
      - 9443
      - 12000
    profiles: ["redis"]
    networks:
      re_cluster:
        ipv4_address: 192.168.20.3

  re3:
    image: redislabs/redis:latest
    container_name: re3
    restart: unless-stopped
    tty: true
    cap_add: 
      - sys_resource
    ports:
      - 8443
      - 9443
      - 12000
    profiles: ["redis"]
    networks:
      re_cluster:
        ipv4_address: 192.168.20.4

networks:
  re_cluster:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.20.0/24
